import { IMeme, MEME_PERMISSION } from "../models";

export const MEMES: IMeme[] = [
  {
    id: "angry",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "banned",
    duration: 8500,
    permission: MEME_PERMISSION.ALL,
    volume: 15,
  },
  {
    id: "bold",
    duration: 6500,
    permission: MEME_PERMISSION.ALL,
    volume: 80,
  },
  {
    id: "bores",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
  {
    id: "but-why",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "cant-read",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 40,
  },
  {
    id: "cars-go-boom",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
  {
    id: "controversial",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 90,
  },
  {
    id: "curb",
    duration: 8500,
    permission: MEME_PERMISSION.ALL,
    volume: 20,
  },
  {
    id: "damage",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 15,
  },
  {
    id: "dance",
    duration: 10500,
    permission: MEME_PERMISSION.ALL,
    volume: 20,
  },
  {
    id: "deal",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "deal-with-it",
    duration: 8500,
    permission: MEME_PERMISSION.ALL,
    volume: 35,
  },
  {
    id: "deserve-this",
    duration: 5500,
    permission: MEME_PERMISSION.ALL,
    volume: 10,
  },
  {
    id: "dont-care-for",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 80,
  },
  {
    id: "doom-trophy",
    duration: 19500,
    permission: MEME_PERMISSION.MODS,
    volume: 10,
  },
  {
    id: "excuse-me",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 20,
  },
  {
    id: "f-you",
    duration: 2000,
    permission: MEME_PERMISSION.ALL,
    volume: 60,
  },
  {
    id: "feeling",
    duration: 11500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
  {
    id: "fight-me",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 90,
  },
  {
    id: "funeral",
    duration: 23500,
    permission: MEME_PERMISSION.ALL,
    volume: 20,
  },
  {
    id: "gift",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "good-news",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
  {
    id: "hate",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 90,
  },
  {
    id: "help-police",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 90,
  },
  {
    id: "bo3-3",
    duration: 28500,
    permission: MEME_PERMISSION.MODS,
    volume: 20,
  },
  {
    id: "bo1-7",
    duration: 28500,
    permission: MEME_PERMISSION.MODS,
    volume: 20,
  },
  {
    id: "hmm",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "mistake",
    duration: 7500,
    permission: MEME_PERMISSION.ALL,
    volume: 40,
  },
  {
    id: "iasip-lands",
    duration: 8500,
    permission: MEME_PERMISSION.ALL,
    volume: 10,
  },
  {
    id: "i-hate",
    duration: 8500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
  {
    id: "in-danger",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "legal",
    duration: 5500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "it-burns",
    duration: 5500,
    permission: MEME_PERMISSION.ALL,
    volume: 80,
  },
  {
    id: "beautiful",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 80,
  },
  {
    id: "its-working",
    duration: 5500,
    permission: MEME_PERMISSION.ALL,
    volume: 60,
  },
  {
    id: "worse",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "kill-me",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 30,
  },
  {
    id: "lesson",
    duration: 5500,
    permission: MEME_PERMISSION.ALL,
    volume: 40,
  },
  {
    id: "let-them-fight",
    duration: 5500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
  {
    id: "mama",
    duration: 6500,
    permission: MEME_PERMISSION.ALL,
    volume: 5,
  },
  {
    id: "meat",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 50,
  },
  {
    id: "milhouse",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 90,
  },
  {
    id: "mind-blown",
    duration: 8500,
    permission: MEME_PERMISSION.ALL,
    volume: 30,
  },
  {
    id: "mother",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "my-hand",
    duration: 11500,
    permission: MEME_PERMISSION.ALL,
    volume: 40,
  },
  {
    id: "neat",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 60,
  },
  {
    id: "noice",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 40,
  },
  {
    id: "nonono",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 20,
  },
  {
    id: "no-power",
    duration: 6500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "notes",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
  {
    id: "not-great",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 80,
  },
  {
    id: "not-like-this",
    duration: 7500,
    permission: MEME_PERMISSION.ALL,
    volume: 90,
  },
  {
    id: "old-man",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 10,
  },
  {
    id: "oh-yeah",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "pointing",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 60,
  },
  {
    id: "pretty-good",
    duration: 6500,
    permission: MEME_PERMISSION.ALL,
    volume: 80,
  },
  {
    id: "red-leader",
    duration: 3500,
    permission: MEME_PERMISSION.MODS,
    volume: 100,
  },
  {
    id: "rookie",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "sacrifice",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 80,
  },
  {
    id: "see-the-baby",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "serious",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "shaddap",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
  {
    id: "sob",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "stew",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 40,
  },
  {
    id: "stop-dont",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 90,
  },
  {
    id: "surprised",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 30,
  },
  {
    id: "tearing-me-apart",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 20,
  },
  {
    id: "bait",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 100,
  },
  {
    id: "this-is-fine",
    duration: 3500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
  {
    id: "wack",
    duration: 7500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
  {
    id: "whoa",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 80,
  },
  {
    id: "whos-mad",
    duration: 4500,
    permission: MEME_PERMISSION.ALL,
    volume: 90,
  },
  {
    id: "witness-me",
    duration: 7500,
    permission: MEME_PERMISSION.ALL,
    volume: 90,
  },
  {
    id: "woohoo",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 80,
  },
  {
    id: "wow",
    duration: 2500,
    permission: MEME_PERMISSION.ALL,
    volume: 40,
  },
  {
    id: "you-lose",
    duration: 7500,
    permission: MEME_PERMISSION.ALL,
    volume: 70,
  },
];
